# Generated by Django 3.1.4 on 2022-02-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_category_chef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='category_id',
            new_name='chef_id',
        ),
    ]
