# Generated by Django 3.1.4 on 2022-02-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20220209_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
