# Generated by Django 3.1.4 on 2022-02-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='prepared_by',
        ),
        migrations.AlterField(
            model_name='chef',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
