# Generated by Django 3.1.4 on 2022-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20220211_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('pending', 'pending'), ('complete', 'complete')], default='incomplete', max_length=20),
        ),
    ]
