# Generated by Django 3.1.4 on 2022-02-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20220214_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
